excerpt_separator: ""
pygments: false
markdown: kramdown
url: http://koelnerhof.github.io/blog
baseurl: http://koelnerhof.github.io
title: Unser Blog
email: 
author: koelnerhof
description:
paginate: 5
paginate_path: blog/page:num
google_analytics: 